spring:
 datasource:
  url: jdbc:mysql://localhost:3306/movieDirectors
  username: root
  password: 12345
  driver-class-name: com.mysql.cj.jdbc.Driver
 redis:
    host: localhost
    port: 6379
    timeout: 10000
 cache:
    type: REDIS
    redis:
      cache-null-values: false
      use-key-prefix: true
      time-to-live: 60000 
 jpa: 
  database-platform: org.hibernate.dialect.MySQL5Dialect
  hibernate.ddl-auto: update




